# Imports

In [48]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import Ridge, RidgeCV
from sklearn.linear_model import SGDRegressor

# Fake datasets

In [4]:
X = np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

# Ridge Regression

In [10]:
ridge_reg = Ridge()

In [11]:
ridge_reg.fit(X, y)

Ridge()

In [13]:
ridge_reg.coef_

array([[2.20388371]])

In [14]:
ridge_reg.intercept_

array([4.47540286])

In [17]:
ridge_reg.solver

'auto'

# Ridge Regression CV

In [49]:
ridge_reg_cv = RidgeCV()

In [50]:
ridge_reg_cv.fit(X, y)

RidgeCV()

In [51]:
ridge_reg_cv.coef_

array([[2.46611966]])

In [52]:
ridge_reg_cv.intercept_

array([4.36186912])

# Using Normal equations to solve ridge Regression

In [30]:
ridge_reg_2 = Ridge(alpha=1, solver='cholesky')

In [31]:
ridge_reg_2.fit(X, y)

Ridge(alpha=1, solver='cholesky')

In [32]:
ridge_reg_2.coef_

array([[2.20388371]])

In [33]:
ridge_reg_2.intercept_

array([4.47540286])

# Using SGDRegressor

In [44]:
sgd_reg = SGDRegressor(alpha=0.1, eta0=0.01, penalty='l2', random_state=42, max_iter=1000)

In [45]:
sgd_reg.fit(X, y.ravel())

SGDRegressor(alpha=0.1, random_state=42)

In [46]:
sgd_reg.coef_

array([1.68688852])

In [47]:
sgd_reg.intercept_

array([4.63117175])